definitions:
  appErrors.ResponseError:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  dto.RegistrationDto:
    properties:
      name:
        maxLength: 100
        minLength: 3
        type: string
      password:
        maxLength: 35
        minLength: 8
        type: string
    required:
    - name
    - password
    type: object
info:
  contact: {}
  description: This is a sample HTTP package with Swagger annotations.
  title: VK-Filmoteka
  version: "1.0"
paths:
  /http/v1/auth/registration:
    post:
      consumes:
      - application/json
      description: Ответом при успешном регистрация получаем свои данные
      produces:
      - application/json
      responses:
        "200":
          description: Данные созданного пользователя
          schema:
            $ref: '#/definitions/dto.RegistrationDto'
        "404":
          description: Ошибка 404
          schema:
            $ref: '#/definitions/appErrors.ResponseError'
      summary: Регистрация пользователя
      tags:
      - auth
swagger: "2.0"
